name: flutter_layout
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^2.0.0
  cupertino_icons: ^1.0.2

  firebase_core: ^1.1.0
  cloud_firestore: ^1.0.7
  firebase_storage: ^10.3.11
  firebase_core_platform_interfere: 4.5.1

dev_dependencies:
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: LeckerliOne
      fonts:
        - asset: assets/Montserrat.ttf
        
  assets:
    - assets/logo.jpg
    - assets/images/

